### PR TITLE
Add missing dependency declaration on Magento_Store

### PR DESCRIPTION
**Pull request by navarr**
Codebase depends on:

* StoreManagerInterface's getWebsite() and getStore() methods
* WebsiteInterface's getCode() method
* StoreInterface's getCode() method

Usage: https://github.com/markshust/magento2-module-extrabodyclasses/blob/master/Observer/AddCodesToBodyClass.php#L39-L40

These exist in versions 100 and 101 and are a major version dependency.

### CODE REVIEW

**Comment by markshust** [comment]
@navarr good catch, I also added it as a dep to the module.xml file. Can you review and let me know if it looks good? Then I'll merge in.

**Comment by navarr** [comment]
@markshust looks good to me. Probably not necessary in module.xml (that's just for xml merging order and install/data scripts, right?), but it can't hurt

**Comment by markshust** [comment]
@navarr I've always been really fuzzy about this. After some research, I think you are right. Since this is declared in `composer.json` since it explicitly uses code from that module, it is considered a "hard dep". Soft deps can function without a composer.json "require", and module.xml is used with those. The module.xml definitely controls the load ordering, which is another reason to have it in module.xml. Since load ordering isn't needed here and it's already declared in composer.json as a hard dep, it doesn't need to be in module.xml.

Ref: https://devdocs.magento.com/guides/v2.4/architecture/archi_perspectives/components/modules/mod_depend.html#soft-dependencies

**Comment by markshust** [comment]
@navarr Now I'm an expert on module deps! 🤡 Thanks for pointing this out https://campus.m.academy/c/peer-teaching/hard-soft-module-dependencies-in-magento-2

**Pull request merged**
